### ISSUE TITLE
ベクトル化する際のengine指定で変数指定漏れ

### ISSUE THREAD

**Issue by rewoso** [AvanadeJapanPublishingQuery/AzureOpenAIServicePracticalGuide-book#1]
[UploadDocument-Vector.py](https://github.com/AvanadeJapanPublishingQuery/AzureOpenAIServicePracticalGuide-book/blob/main/Chapter-05-Azure-OpenAI-Tools-and-Techniques/Section-03-Azure-AI-Search/python/5.3.6.Vector-Search/UploadDocument-Vector.py) の56行目で、engineパラメータに対して固定値が設定されています。

> response_description = openai.Embedding.create(input=doc['description'],engine='text-embedding-ada-002')

正しくは下記52行目のようにmodel_name変数を指定する必要があります。
>  response_title = openai.Embedding.create(input=doc['title'],engine=model_name)

※書籍内のテキストはmodel_name変数が利用されています

**Comment by AvanadeJapanPublishingQuery** [comment]
ご指摘ありがとうございます。

ご指摘頂いた通り、サンプルコードの52行目が間違っておりましたのでサンプルコードの修正を致しました。
テキスト ５章 5.3.6 Pythonでの構築手順 (ベクトル検索) P.183のサンプルコードの中央付近に該当します。
テキストの修正はございません。

変更前
   response_description = openai.Embedding.create(input=doc['description'],engine='text-embedding-ada-002')
   
 変更後
   response_description = openai.Embedding.create(input=doc['description'],engine=model_name)

**Comment by AvanadeJapanPublishingQuery** [comment]
修正対応しました。
