### ISSUE TITLE
5.6章で使用されるlong_text.txtの所在

### ISSUE THREAD

**Issue by BanquetKuma** [AvanadeJapanPublishingQuery/AzureOpenAIServicePracticalGuide-book#3]
P240に記載されているlong_text.txtが5.6章のリポジトリの中に見当たりませんでした。
どこに保存されていますでしょうか？

**Comment by AvanadeJapanPublishingQuery** [comment]
ご指摘ありがとうございます。
ご指摘頂いた通り、リポジトリに P240に記載の long_text.txt が登録されれおりませんでした。
5.6章のリポジトリの中に新しく登録して対応致しました。
https://github.com/AvanadeJapanPublishingQuery/AzureOpenAIServicePracticalGuide-book/tree/main/Chapter-05-Azure-OpenAI-Tools-and-Techniques/Section-06-LangChain/Text

**Comment by AvanadeJapanPublishingQuery** [comment]
対策終了のため、コミット致します。
